# Generated by Django 4.1 on 2022-08-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='spaciality',
        ),
    ]
