# Generated by Django 4.1 on 2022-08-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_doctor_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='spaciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.departement'),
        ),
    ]
