# Generated by Django 4.1 on 2022-09-02 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_doctor_spaciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.departement'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='tarif',
            field=models.PositiveIntegerField(),
        ),
    ]
