# Generated by Django 4.1 on 2022-08-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about', models.CharField(max_length=30)),
                ('description_about', models.TextField()),
                ('image_about', models.ImageField(upload_to='about_img')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=30)),
                ('email_contact', models.EmailField(max_length=254)),
                ('subject_contact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=50)),
                ('email_site', models.EmailField(max_length=254)),
                ('phone_site', models.CharField(max_length=15)),
                ('address_site', models.CharField(max_length=50)),
                ('copyright_site', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_link', models.CharField(max_length=15)),
                ('icon_link', models.CharField(max_length=15)),
                ('link_link', models.URLField(max_length=100)),
            ],
        ),
    ]
