# Generated by Django 4.0.5 on 2022-08-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_img')),
                ('label1', models.CharField(blank=True, max_length=100, null=True)),
                ('label2', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteinfos',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteinfos',
            name='media_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.sociallink'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siteinfos',
            name='email_site',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfos',
            name='phone_site',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
