# Generated by Django 4.0.5 on 2022-08-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_about_description_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon_link',
            field=models.CharField(max_length=50),
        ),
    ]
