# Generated by Django 4.0.5 on 2022-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
